baseURL = "https://carol-hsu.github.io/"
title = "Carol Hsu's Blog"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = false
rssLimit = 20 
disqusShortname = ""
googleAnalytics = "G-B4DQYNDLVV"
copyright = ""
enableGitInfo = true

defaultContentLanguage = "en"

[pagination]
  pagerSize = 3   

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"


#[[menu.main]]
#  name = "About"
#  weight = 10
#  identifier = "about"
#  pageref = "/about.md"
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  pageref = "/"
## put "about" with weight 20
[[menu.main]]
  name = "Post"
  weight = 30
  identifier = "post"
  pageref = "/post/"
[[menu.main]]
  name = "Tag"
  weight = 40
  identifier = "tags"
  pageref = "/tags/"

#[[menu.main]]
#  name = "external-link"
#  weight = 50
#  pageref = "https://gohugo.io"


[params]
  since = "2025"  
  homeFullContent = false
  rssFullContent = true   

  author.name = "Carol Hsu"
  author.email = "asymplone@gmail.com"
  author.url = "/about"

  # site info (optional)
  logoTitle = "( à©­Ë™á—œË™)à©­ðŸ¥Ÿ"
  keywords = ["Linux", "Rust", "eBPF"]
  description = "The studying journey of computer systems."

  dateFormatToUse = "2006-01-02"

  toc = true
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe
  contentCopyright = "All rights reserved. Feel free to reach out with any questions."

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.gitInfo]
    gitRepo = "https://github.com/carol-hsu/carol-hsu.github.io"
    showCommitMessage = false

  [params.social]
    e-linkedin = "https://www.linkedin.com/in/ke-jou-hsu"
    g-github = "https://github.com/carol-hsu" 
